### ISSUE TITLE
【BUG】ViewGroup﹕ addInArray been called....

### ISSUE THREAD

**Issue by xiaomeixw** [bingoogolapple/BGABanner-Android#19]
D/ViewGroup﹕ addInArray been called, this = ui.banner.BGAViewPager{41cfd120 VFED.... ......ID 0,0-1280,752}call stack =
    java.lang.Throwable: addInArray
            at android.view.ViewGroup.addInArray(ViewGroup.java:3786)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3740)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3687)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3668)
            at android.support.v4.view.ViewPager.addView(ViewPager.java:1339)
            at android.view.ViewGroup.addView(ViewGroup.java:3509)
            at android.view.ViewGroup.addView(ViewGroup.java:3485)
            at ui.banner.BGABanner$PageAdapter.instantiateItem(BGABanner.java:504)
            at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:869)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1053)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:16834)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:824)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:500)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2368)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2252)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1315)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1513)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
            at android.os.Handler.handleCallback(Handler.java:808)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5333)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by xiaomeixw** [comment]
The bug hapeen on this line :

        @Override
        public Object instantiateItem(ViewGroup container, int position) {
            View view = mViews.get(position % mViews.size());
            // 在destroyItem方法中销毁的话，当只有3页时会有问题
            if (container.equals(view.getParent())) {
                container.removeView(view);
            }
            container.addView(view);

            return view;
        }

**Comment by MathanSara** [comment]
thank u .. but am using .. recycle view .. how to modifies my program

**Comment by bingoogolapple** [comment]
@xiaomeixw 麻烦试一下最新版本v2.0.6还有没有这个问题，谢谢

**Comment by bingoogolapple** [comment]
v2.2.3
