### ISSUE TITLE
如下错误

### ISSUE THREAD

**Issue by ximencx** [bingoogolapple/BGABanner-Android#20]
`05-04 11:06:11.800 18875-18875/com.apicloud.A6984334434180 E/x_log:ViewInjectorImpl.inject(L:111): Binary XML file line #56: Error inflating class cn.bingoogolapple.bgabanner.BGABanne
                                                                                                   android.view.InflateException: Binary XML file line #56: Error inflating class cn.bingoogolapple.bgabanner.BGABanne
                                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                                       at org.xutils.view.ViewInjectorImpl.inject(ViewInjectorImpl.java:107)
                                                                                                       at com.apicloud.A6984334434180.base.BaseFragment.onCreateView(BaseFragment.java:84)
                                                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                                                                       at com.apicloud.A6984334434180.base.BaseFragmentActivity.onStart(BaseFragmentActivity.java:29)
                                                                                                       at com.apicloud.A6984334434180.ui.activity.HomeActivity.onStart(HomeActivity.java:166)
                                                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
                                                                                                       at android.app.Activity.performStart(Activity.java:5953)
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.bingoogolapple.bgabanner.BGABanne" on path: DexPathList[[zip file "/data/app/com.apicloud.A6984334434180-2/base.apk"],nativeLibraryDirectories=[/data/app/com.apicloud.A6984334434180-2/lib/x86, /vendor/lib, /system/lib]]
                                                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:571)
                                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                                       at org.xutils.view.ViewInjectorImpl.inject(ViewInjectorImpl.java:107) 
                                                                                                       at com.apicloud.A6984334434180.base.BaseFragment.onCreateView(BaseFragment.java:84) 
                                                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
                                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
                                                                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
                                                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
                                                                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
                                                                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
                                                                                                       at com.apicloud.A6984334434180.base.BaseFragmentActivity.onStart(BaseFragmentActivity.java:29) 
                                                                                                       at com.apicloud.A6984334434180.ui.activity.HomeActivity.onStart(HomeActivity.java:166) 
                                                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220) 
                                                                                                       at android.app.Activity.performStart(Activity.java:5953) 
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261) 
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
                                                                                                   	Suppressed: java.lang.ClassNotFoundException: Didn't find class "cn.bingoogolapple.bgabanner.BGABanne" on path: DexPathList[[dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-support-annotations-23.3.0_def2b22731fbd5fe0a93167c36ba1fec33805f7d-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.apicloud.A6984334434180/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/da
`

**Comment by bingoogolapple** [comment]
@ximencx 这个问题解决了吗？

如果还没有解决能描述一下你布局文件的嵌套结构吗？

**Comment by ximencx** [comment]
群主 时间太长忘了  这个issue可以关了
