### ISSUE TITLE
Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by Handy045** [bingoogolapple/BGABanner-Android#215]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.handy.app/com.handy.frame.module.guide.GuideActivity}: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2740)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1486)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6166)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at cn.bingoogolapple.bgabanner.BGABanner.setEnterSkipViewIdAndDelegate(BGABanner.java:447)
        at com.handy.frame.module.guide.GuideActivity.initViewHDB(GuideActivity.java:85)
        at com.handy.base.app.BaseActivity.onStart(BaseActivity.java:137)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
        at android.app.Activity.performStart(Activity.java:6768)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2642)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2740) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1486) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6166) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Handy045** [comment]
compileSdkVersion: 28
minSdkVersion : 19
targetSdkVersion : 28

com.android.support:appcompat-v7 : "28.0.0"

com.android.tools.build:gradle:3.4.0

**Comment by Handy045** [comment]
希望可以给图片指示点设置大小或者内置固定大小。指示器图片压缩到28x28后会出现模糊的情况。

**Comment by bingoogolapple** [comment]
1、类型转换异常和这个库没关系，再检查一下你项目中取 context 的方式
2、指示器可以自定义，具体大小得看你指定的图片大小或指定的 shape 中的 size
![image](https://user-images.githubusercontent.com/8949716/68064137-c245a300-fd52-11e9-96e8-9e5362f03502.png)

![image](https://user-images.githubusercontent.com/8949716/68064135-b8bc3b00-fd52-11e9-8202-202786b49534.png)
