### ISSUE TITLE
找不到java.lang.ClassNotFoundException: Didn't find class "cn.bingoogolapple.bgabanner.BGABanner" on path: DexPathList[[zip file "/data/app/com.ytlz.testbanner-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ytlz.testbanner-2/lib/arm64, /system/lib64, /vendor/lib64]]

### ISSUE THREAD

**Issue by 121104115wyb** [bingoogolapple/BGABanner-Android#222]
我使用as开发，新建一个moudle使用build方式引入BGABanner，然后把这个mudle打成arr包，在新的工程下引用这个arr包，一直提示找不到找不到java.lang.ClassNotFoundException: Didn't find class "cn.bingoogolapple.bgabanner.BGABanner" on path: DexPathList；请问博主这个怎么解决啊，我新建一个项目又测试了一遍还是不行，尝试build ，clean ，重启as，重新打包，项目也没有使用重复的应用，也没有使用分包模式，尝试降低版本到  2.2.1 还是报同样的错误

**Comment by 121104115wyb** [comment]
2019-06-06 16:10:53.663 24831-24831/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ytlz.testbanner, PID: 24831
    java.lang.NoClassDefFoundError: Failed resolution of: Lcn/bingoogolapple/bgabanner/BGABanner;
        at com.ytlz.mylibrary.TestActivity.onCreate(TestActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:6709)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2650)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6216)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.bingoogolapple.bgabanner.BGABanner" on path: DexPathList[[zip file "/data/app/com.ytlz.testbanner-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ytlz.testbanner-2/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.ytlz.mylibrary.TestActivity.onCreate(TestActivity.java:16) 
        at android.app.Activity.performCreate(Activity.java:6709) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2650) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6216) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)

**Comment by 121104115wyb** [comment]
问题已经解决
