### ISSUE TITLE
三星手机点击查看ListView HeaderView Demo报java.lang.VerifyError: cn/bingoogolapple/androidcommon/adapter/BGAViewHolderHelper

### ISSUE THREAD

**Issue by yanchengmeng** [bingoogolapple/BGABanner-Android#57]
java.lang.VerifyError: cn/bingoogolapple/androidcommon/adapter/BGAViewHolderHelper
                                                                                      at cn.bingoogolapple.androidcommon.adapter.BGAAdapterViewHolder.<init>(BGAAdapterViewHolder.java:35)
                                                                                      at cn.bingoogolapple.androidcommon.adapter.BGAAdapterViewHolder.dequeueReusableAdapterViewHolder(BGAAdapterViewHolder.java:48)
                                                                                      at cn.bingoogolapple.androidcommon.adapter.BGAAdapterViewAdapter.getView(BGAAdapterViewAdapter.java:64)
                                                                                      at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
                                                                                      at android.widget.AbsListView.obtainView(AbsListView.java:2733)
                                                                                      at android.widget.ListView.makeAndAddView(ListView.java:1811)
                                                                                      at android.widget.ListView.fillDown(ListView.java:697)
                                                                                      at android.widget.ListView.fillSpecific(ListView.java:1360)
                                                                                      at android.widget.ListView.layoutChildren(ListView.java:1619)
                                                                                      at android.widget.AbsListView.onLayout(AbsListView.java:2546)
                                                                                      at android.view.View.layout(View.java:15664)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4869)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                      at android.view.View.layout(View.java:15664)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4869)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
                                                                                      at android.view.View.layout(View.java:15664)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4869)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                      at android.view.View.layout(View.java:15664)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4869)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2246)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1200)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:573)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
                                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:157)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by bingoogolapple** [comment]
用最新版试试
